function  s  = frame_to_pyton_pose( T,name )
%FRAME_TO_PYTON_POSE Summary of this function goes here
%   Detailed explanation goes here
q= Quaternion (T(1:3,1:3));
qd= q.double% first one is w

s=[name,'=Pose();',...
   name,'.position.x=',num2str(T(1,4)),';',... 
   name,'.position.y=',num2str(T(2,4)),';',... 
   name,'.position.z=',num2str(T(3,4)),';',... 
   name,'.orientation.w=',num2str(qd(1)),';',...
   name,'.orientation.x=',num2str(qd(2)),';',...
   name,'.orientation.y=',num2str(qd(3)),';',...
   name,'.orientation.z=',num2str(qd(4))]
end

